### ISSUE TITLE
npm install command does not create the artifacts

### ISSUE THREAD

**Issue by ragdeshp** [IBM/BlockchainPublicRegulationFabric-Food#5]
Hello, I did a git clone and ran the npm install and it showed an error. It was to do with the python version. Hence ran the command npm install --python=python2.7, but still the command fails to extract the code.
Log are as follows:
mkdirp ./dist && composer archive create --sourceType dir --sourceName . -a ./dist/food-supply.bna

/Users/raghavendradeshpande/Documents/2018/May/BlockchainPublicRegulationFabric-Food/node_modules/composer-common/lib/cardstore/businessnetworkcardstore.js:54
    async get(cardName) {
          ^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/raghavendradeshpande/Documents/2018/May/BlockchainPublicRegulationFabric-Food/node_modules/composer-common/index.js:56:43)

npm WARN food-supply@0.0.1 No repository field.
npm ERR! Darwin 17.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--python=python2.7"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! food-supply@0.0.1 prepublish: `mkdirp ./dist && composer archive create --sourceType dir --sourceName . -a ./dist/food-supply.bna`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the food-supply@0.0.1 prepublish script 'mkdirp ./dist && composer archive create --sourceType dir --sourceName . -a ./dist/food-supply.bna'.

**Comment by ljbennett62** [comment]
@ragdeshp - updated the code - please try it again

**Comment by ljbennett62** [comment]
@ragdeshp - this is similar to your previous issue - see [StackOverflow response](https://stackoverflow.com/questions/49744276/error-cannot-find-module-api-hyperledger-composer) - because many times the errors you see with Composer are derived in having installed either the wrong Node version or took an approach that is not supported by Composer
