### ISSUE TITLE
npm install error logs

### ISSUE THREAD

**Issue by ragdeshp** [IBM/BlockchainPublicRegulationFabric-Food#6]
npm install
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> food-supply@0.0.1 prepublish /Users/raghavendradeshpande/Documents/2018/May/BlockchainPublicRegulationFabric-Food
> mkdirp ./dist && composer archive create --sourceType dir --sourceName . -a ./dist/food-supply.bna

/Users/raghavendradeshpande/Documents/2018/May/BlockchainPublicRegulationFabric-Food/node_modules/composer-common/lib/cardstore/businessnetworkcardstore.js:54
    async get(cardName) {
          ^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/raghavendradeshpande/Documents/2018/May/BlockchainPublicRegulationFabric-Food/node_modules/composer-common/index.js:56:43)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! food-supply@0.0.1 prepublish: `mkdirp ./dist && composer archive create --sourceType dir --sourceName . -a ./dist/food-supply.bna`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the food-supply@0.0.1 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/raghavendradeshpande/.npm/_logs/2018-05-18T10_27_29_780Z-debug.log

**Comment by ljbennett62** [comment]
@ragdeshp - code has been updated - please try it again

**Comment by ljbennett62** [comment]
@ragdeshp - please note that Composer is finicky with the installation of Node.  You need to make sure you install `nvm` (V5.6.0 or higher); use that to install node and explicitly state that you are using node version 8.11.3.
